export const COLOR_GRADE_MULTIPLIERS = {
  CYBERPUNK_SATURATE: 1.5,
  CYBERPUNK_CONTRAST: 1.2,

  VINTAGE_CONTRAST: 0.9,
  VINTAGE_SATURATE: 0.8,

  NOIR_CONTRAST: 1.5,

  CINEMATIC_CONTRAST: 1.2,
  CINEMATIC_SATURATE: 1.1,

  DREAMY_CONTRAST: 0.85,
  DREAMY_SATURATE: 1.3,
  DREAMY_BRIGHTNESS: 1.15,

  VHS_CONTRAST: 1.3,
  VHS_SATURATE: 0.8,

  WARM_CONTRAST: 1.05,
  WARM_SATURATE: 1.2,
} as const;
