export const ANIME = {
  DEFAULT_SHADOW_STEPS: 3,
  DEFAULT_SHADOW_THRESHOLD: 0.5,
  DEFAULT_HIGHLIGHT_SHARPNESS: 0.7,
  DEFAULT_OUTLINE_WIDTH: 1.5,
  DEFAULT_SKIN_TONE_BOOST: 0.3,
} as const;

export const CEL = {
  DEFAULT_COLOR_BANDS: 3,
  DEFAULT_OUTLINE_THICKNESS: 2.0,
  DEFAULT_HALFTONE_SIZE: 0,
  DEFAULT_SPECULAR_SIZE: 0.3,
} as const;

export const CRYSTAL = {
  DEFAULT_IOR: 1.5,
  DEFAULT_DISPERSION: 0.02,
  DEFAULT_FRESNEL_POWER: 2.5,
  DEFAULT_TRANSMISSION: 0.9,
  DEFAULT_CAUSTICS: 0.4,
} as const;

export const DEPTH_VARIANCE_DEFAULT = 0.5;

export const EDGE_FADE = {
  SEAM_CORRECTION_DEFAULT: 0.0,
  EDGE_FADE_DEFAULT: 0.8,
  SMOOTHSTEP_EDGE: 0.08,
  SEAM_CORRECTION_THRESHOLD: 0.5,
  BLEND_WIDTH: 0.1,
  LEFT_SAMPLE: 0.01,
  RIGHT_SAMPLE: 0.99,
  AVERAGE_MULTIPLIER: 0.5,
} as const;

export const HOLOGRAM_V2 = {
  DEFAULT_SCANLINE_INTENSITY: 0.6,
  DEFAULT_SCANLINE_DENSITY: 50,
  DEFAULT_RGB_OFFSET: 0.005,
  DEFAULT_FLICKER_SPEED: 2.0,
  DEFAULT_GLITCH_INTENSITY: 0.3,
  DEFAULT_FRESNEL_POWER: 2.0,
  DEFAULT_DATA_STREAM_SPEED: 1.5,
} as const;

export const INK_WASH = {
  DEFAULT_INK_DENSITY: 0.7,
  DEFAULT_BLEED_AMOUNT: 0.5,
  DEFAULT_PAPER_TEXTURE: 0.4,
  DEFAULT_BRUSH_TEXTURE: 0.6,
  DEFAULT_WHITE_SPACE: 0.3,
  DEFAULT_EDGE_WOBBLE: 0.4,
} as const;

export const MATERIAL_DEFAULTS = {
  ENV_MAP_INTENSITY: 0.8,
  EMISSIVE_INTENSITY: 0,
  EMISSIVE_COLOR: '#000000',
} as const;

export const MATRIX = {
  DEFAULT_FALL_SPEED: 2.0,
  DEFAULT_CHAR_DENSITY: 0.6,
  DEFAULT_GLOW_INTENSITY: 1.2,
  DEFAULT_TRAIL_LENGTH: 0.5,
  DEFAULT_CHAR_SIZE: 8.0,
  DEFAULT_SHOW_ORIGINAL: 0.3,
} as const;

export const RETRO_PIXEL = {
  DEFAULT_PIXEL_SIZE: 4,
  DEFAULT_PALETTE_MODE: 0,
  DEFAULT_DITHER_STRENGTH: 0.5,
  DEFAULT_CRT_EFFECT: 0.3,
  DEFAULT_COLOR_DEPTH: 16,
  DEFAULT_SCANLINE_BRIGHTNESS: 0.85,
} as const;

export const TEXTURE = {
  DEFAULT_TEXEL_SIZE: 512,
} as const;
