import animeFragment from './anime/fragment.glsl';
import animeVertex from './anime/vertex.glsl';
import celFragment from './cel/fragment.glsl';
import celVertex from './cel/vertex.glsl';
import edgeFadeChunk from './common/edge_fade.glsl';
import luminanceChunk from './common/luminance.glsl';
import noiseChunk from './common/noise.glsl';
import seamCorrectionChunk from './common/seam_correction.glsl';
import crystalFragment from './crystal/fragment.glsl';
import crystalVertex from './crystal/vertex.glsl';
import hologramV2Fragment from './hologram_v2/fragment.glsl';
import hologramV2Vertex from './hologram_v2/vertex.glsl';
import inkWashFragment from './ink_wash/fragment.glsl';
import inkWashVertex from './ink_wash/vertex.glsl';
import matrixFragment from './matrix/fragment.glsl';
import matrixVertex from './matrix/vertex.glsl';
import normalFragment from './normal/fragment.glsl';
import normalVertex from './normal/vertex.glsl';
import retroPixelFragment from './retro_pixel/fragment.glsl';
import retroPixelVertex from './retro_pixel/vertex.glsl';

export const animeFragmentShader = animeFragment;
export const animeVertexShader = animeVertex;
export const celFragmentShader = celFragment;
export const celVertexShader = celVertex;
export const crystalFragmentShader = crystalFragment;
export const crystalVertexShader = crystalVertex;
export const EDGE_FADE_CHUNK = edgeFadeChunk;
export const hologramV2FragmentShader = hologramV2Fragment;
export const hologramV2VertexShader = hologramV2Vertex;
export const inkWashFragmentShader = inkWashFragment;
export const inkWashVertexShader = inkWashVertex;
export const LUMINANCE_CHUNK = luminanceChunk;
export const matrixFragmentShader = matrixFragment;
export const matrixVertexShader = matrixVertex;
export const NOISE_CHUNK = noiseChunk;
export const normalFragmentShader = normalFragment;
export const normalVertexShader = normalVertex;
export const retroPixelFragmentShader = retroPixelFragment;
export const retroPixelVertexShader = retroPixelVertex;
export const SEAM_CORRECTION_CHUNK = seamCorrectionChunk;
