export const IMAGE_ANALYSIS = {
  LOW_CONTRAST_THRESHOLD: 0.2,
  DARK_THRESHOLD: 0.3,
  RGB_WEIGHT_R: 0.299,
  RGB_WEIGHT_G: 0.587,
  RGB_WEIGHT_B: 0.114,
  MAX_COLOR_VALUE: 255,
  CONTRAST_DIVISOR: 128,
  SAMPLE_STEP: 4,
  CONTRAST_SAMPLE_STEP: 16,
  HEX_BASE: 16,
  HEX_PAD_LENGTH: 2,
} as const;

export const VIGNETTE = {
  BASE_OPACITY: 0.2,
  STRENGTH_MULTIPLIER: 0.8,
} as const;
