export const PERFORMANCE_MONITOR = {
  TARGET_FPS: 60,
  TARGET_FRAME_TIME_MS: 16.67,
  MAX_FRAME_SAMPLES: 60,
  MIN_SAMPLES_FOR_CALC: 10,
  FPS_DECIMAL_PRECISION: 10,
  FRAME_TIME_DECIMAL_PRECISION: 100,
  OPTIMIZE_COOLDOWN_MS: 5000,
  HIGH_TRIANGLE_COUNT: 500000,
  MS_PER_SECOND: 1000,
  BYTES_PER_KB: 1024,
} as const;

export const EVENT_BUS = {
  MAX_HISTORY: 100,
} as const;
