export const BATCH_PROCESSING = {
  DEFAULT_BATCH_SIZE: 10,
} as const;
export const EASING = {
  QUAD_MULTIPLIER: 2,
  QUAD_OFFSET: 4,

  CUBIC_MULTIPLIER: 4,
  CUBIC_POWER: 3,
  CUBIC_DIVISOR: 2,

  ELASTIC_BASE: 2,
  ELASTIC_EXPONENT: 10,
  ELASTIC_OFFSET: 10,
  ELASTIC_PHASE_OFFSET: 10.75,
  ELASTIC_PERIOD_DIVISOR: 3,
  ELASTIC_IN_OUT_MULTIPLIER: 20,
  ELASTIC_IN_OUT_PHASE_OFFSET: 11.125,
  ELASTIC_IN_OUT_PERIOD_DIVISOR: 4.5,

  BOUNCE_N1: 7.5625,
  BOUNCE_D1: 2.75,
  BOUNCE_THRESHOLD_1: 1,
  BOUNCE_THRESHOLD_2: 2,
  BOUNCE_THRESHOLD_3: 2.5,
  BOUNCE_OFFSET_1: 1.5,
  BOUNCE_OFFSET_2: 2.25,
  BOUNCE_OFFSET_3: 2.625,
  BOUNCE_RESULT_1: 0.75,
  BOUNCE_RESULT_2: 0.9375,
  BOUNCE_RESULT_3: 0.984375,

  HALF: 0.5,
} as const;
export const IMAGE_PROCESSING = {
  LUMINANCE_R: 0.299,
  LUMINANCE_G: 0.587,
  LUMINANCE_B: 0.114,

  MAX_COLOR_VALUE: 255,
  RGBA_CHANNELS: 4,

  DEPTH_MAX_SIZE: 2048,
  DEPTH_CONTRAST_MAX: 2.0,
  DEPTH_GRADIENT_POWER: 0.7,
  DEPTH_EDGE_THRESHOLD: 128,
  DEPTH_LUM_WEIGHT_BASE: 0.5,
  DEPTH_LUM_WEIGHT_RANGE: 0.3,
  DEPTH_FINE_BLUR_RADIUS: 2,
  DEPTH_COARSE_BLUR_RADIUS: 8,
  DEPTH_JPEG_QUALITY: 0.9,

  SOBEL_KERNEL_SIZE: 3,

  BLUR_CANVAS_SIZE: 256,
  BLUR_AMOUNT: 20,
  BLUR_OFFSET: -20,
  BLUR_DRAW_SIZE: 296,
  BLUR_OVERLAY_ALPHA: 0.4,
  BLUR_JPEG_QUALITY: 0.7,

  RESIZE_DEFAULT_MAX: 512,
  RESIZE_JPEG_QUALITY: 0.8,
} as const;
export const MATH = {
  DEGREES_IN_HALF_CIRCLE: 180,
} as const;
export const MEMORY = {
  BYTES_PER_KB: 1024,
  PERCENTAGE_MULTIPLIER: 100,
} as const;
export const VIDEO_PROCESSING = {
  DEFAULT_MAX_DIMENSION: 4096,
  FALLBACK_DIMENSION: 1024,
  DEFAULT_TIMEOUT_MS: 60000,
  JPEG_QUALITY: 0.9,

  DEFAULT_SEEK_TIME: 0.1,
  SEEK_DURATION_RATIO: 0.1,
  MAX_SEEK_TIME: 1.0,
} as const;
