spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
minio.url=http://localhost:9000
minio.access-key=test
minio.secret-key=testpassword
minio.bucket=test-bucket
