export const BRIGHTNESS = {
  MIN: 0.5,
  MAX: 2,
  STEP: 0.05,
} as const;
export const CONTRAST = {
  MIN: 0.5,
  MAX: 2,
  STEP: 0.05,
} as const;
export const EXPOSURE = {
  MIN: 0.5,
  MAX: 3,
  STEP: 0.1,
} as const;
export const LIGHT_INTENSITY = {
  MIN: 0.5,
  MAX: 3,
  STEP: 0.1,
} as const;
export const MATERIAL = {
  ROUGHNESS_MIN: 0,
  ROUGHNESS_MAX: 1,
  ROUGHNESS_STEP: 0.05,
  METALNESS_MIN: 0,
  METALNESS_MAX: 1,
  METALNESS_STEP: 0.05,
} as const;
export const SATURATION = {
  MIN: 0,
  MAX: 2,
  STEP: 0.05,
} as const;
export const VIGNETTE = {
  STRENGTH_MIN: 0,
  STRENGTH_MAX: 1,
  STRENGTH_STEP: 0.05,
} as const;

export const ANIME = {
  SHADOW_STEPS_MIN: 2,
  SHADOW_STEPS_MAX: 6,
  SHADOW_STEPS_STEP: 1,
  DEFAULT_SHADOW_STEPS: 4,        // 更多层次 (原 3)
  SHADOW_THRESHOLD_MIN: 0.1,
  SHADOW_THRESHOLD_MAX: 0.9,
  SHADOW_THRESHOLD_STEP: 0.05,
  DEFAULT_SHADOW_THRESHOLD: 0.45, // 更柔和 (原 0.5)
  HIGHLIGHT_SHARPNESS_MIN: 0,
  HIGHLIGHT_SHARPNESS_MAX: 1,
  HIGHLIGHT_SHARPNESS_STEP: 0.05,
  DEFAULT_HIGHLIGHT_SHARPNESS: 0.8,  // 更锐利 (原 0.7)
  OUTLINE_WIDTH_MIN: 0.5,
  OUTLINE_WIDTH_MAX: 3,
  OUTLINE_WIDTH_STEP: 0.1,
  DEFAULT_OUTLINE_WIDTH: 1.2,     // 更细腻 (原 1.5)
  SKIN_TONE_BOOST_MIN: 0,
  SKIN_TONE_BOOST_MAX: 1,
  SKIN_TONE_BOOST_STEP: 0.05,
  DEFAULT_SKIN_TONE_BOOST: 0.4,   // 更明显 (原 0.3)
} as const;

export const CEL = {
  COLOR_BANDS_MIN: 2,
  COLOR_BANDS_MAX: 8,
  COLOR_BANDS_STEP: 1,
  DEFAULT_COLOR_BANDS: 4,         // 更多层次 (原 3)
  OUTLINE_THICKNESS_MIN: 0.5,
  OUTLINE_THICKNESS_MAX: 5,
  OUTLINE_THICKNESS_STEP: 0.5,
  DEFAULT_OUTLINE_THICKNESS: 1.8, // 更细 (原 2)
  HALFTONE_SIZE_MIN: 0,
  HALFTONE_SIZE_MAX: 10,
  HALFTONE_SIZE_STEP: 0.5,
  DEFAULT_HALFTONE_SIZE: 2,       // 添加半调 (原 0)
  SPECULAR_SIZE_MIN: 0,
  SPECULAR_SIZE_MAX: 1,
  SPECULAR_SIZE_STEP: 0.05,
  DEFAULT_SPECULAR_SIZE: 0.35,    // 略大 (原 0.3)
} as const;

export const CRYSTAL = {
  IOR_MIN: 1.1,
  IOR_MAX: 2.5,
  IOR_STEP: 0.05,
  DEFAULT_IOR: 1.45,              // 更自然 (原 1.5)
  DISPERSION_MIN: 0,
  DISPERSION_MAX: 0.1,
  DISPERSION_STEP: 0.005,
  DEFAULT_DISPERSION: 0.025,      // 更明显 (原 0.02)
  FRESNEL_POWER_MIN: 1,
  FRESNEL_POWER_MAX: 5,
  FRESNEL_POWER_STEP: 0.1,
  DEFAULT_FRESNEL_POWER: 2.8,     // 更强 (原 2.5)
  TRANSMISSION_MIN: 0.5,
  TRANSMISSION_MAX: 1,
  TRANSMISSION_STEP: 0.05,
  DEFAULT_TRANSMISSION: 0.92,     // 更透明 (原 0.9)
  CAUSTICS_MIN: 0,
  CAUSTICS_MAX: 1,
  CAUSTICS_STEP: 0.05,
  DEFAULT_CAUSTICS: 0.5,          // 更明显 (原 0.4)
} as const;

export const HOLOGRAM_V2 = {
  SCANLINE_INTENSITY_MIN: 0,
  SCANLINE_INTENSITY_MAX: 1,
  SCANLINE_INTENSITY_STEP: 0.05,
  DEFAULT_SCANLINE_INTENSITY: 0.5, // 更柔和 (原 0.6)
  SCANLINE_DENSITY_MIN: 10,
  SCANLINE_DENSITY_MAX: 100,
  SCANLINE_DENSITY_STEP: 5,
  DEFAULT_SCANLINE_DENSITY: 60,    // 更密 (原 50)
  RGB_OFFSET_MIN: 0,
  RGB_OFFSET_MAX: 0.02,
  RGB_OFFSET_STEP: 0.001,
  DEFAULT_RGB_OFFSET: 0.004,       // 更细微 (原 0.005)
  FLICKER_SPEED_MIN: 0,
  FLICKER_SPEED_MAX: 5,
  FLICKER_SPEED_STEP: 0.1,
  DEFAULT_FLICKER_SPEED: 1.5,      // 更慢 (原 2)
  GLITCH_INTENSITY_MIN: 0,
  GLITCH_INTENSITY_MAX: 1,
  GLITCH_INTENSITY_STEP: 0.05,
  DEFAULT_GLITCH_INTENSITY: 0.25,  // 更轻 (原 0.3)
  FRESNEL_POWER_MIN: 0.5,
  FRESNEL_POWER_MAX: 5,
  FRESNEL_POWER_STEP: 0.1,
  DEFAULT_FRESNEL_POWER: 2.2,      // 调整 (原 2)
  DATA_STREAM_SPEED_MIN: 0,
  DATA_STREAM_SPEED_MAX: 3,
  DATA_STREAM_SPEED_STEP: 0.1,
  DEFAULT_DATA_STREAM_SPEED: 1.2,  // 更慢 (原 1.5)
} as const;

export const INK_WASH = {
  INK_DENSITY_MIN: 0.3,
  INK_DENSITY_MAX: 1,
  INK_DENSITY_STEP: 0.05,
  DEFAULT_INK_DENSITY: 0.75,       // 更浓 (原 0.7)
  BLEED_AMOUNT_MIN: 0,
  BLEED_AMOUNT_MAX: 1,
  BLEED_AMOUNT_STEP: 0.05,
  DEFAULT_BLEED_AMOUNT: 0.6,       // 更明显 (原 0.5)
  PAPER_TEXTURE_MIN: 0,
  PAPER_TEXTURE_MAX: 1,
  PAPER_TEXTURE_STEP: 0.05,
  DEFAULT_PAPER_TEXTURE: 0.5,      // 更明显 (原 0.4)
  BRUSH_TEXTURE_MIN: 0,
  BRUSH_TEXTURE_MAX: 1,
  BRUSH_TEXTURE_STEP: 0.05,
  DEFAULT_BRUSH_TEXTURE: 0.7,      // 更强 (原 0.6)
  WHITE_SPACE_MIN: 0,
  WHITE_SPACE_MAX: 1,
  WHITE_SPACE_STEP: 0.05,
  DEFAULT_WHITE_SPACE: 0.35,       // 略多 (原 0.3)
  EDGE_WOBBLE_MIN: 0,
  EDGE_WOBBLE_MAX: 1,
  EDGE_WOBBLE_STEP: 0.05,
  DEFAULT_EDGE_WOBBLE: 0.35,       // 更自然 (原 0.4)
} as const;

export const MATRIX = {
  FALL_SPEED_MIN: 0.5,
  FALL_SPEED_MAX: 5,
  FALL_SPEED_STEP: 0.1,
  DEFAULT_FALL_SPEED: 1.8,         // 更慢 (原 2)
  CHAR_DENSITY_MIN: 0.3,
  CHAR_DENSITY_MAX: 1,
  CHAR_DENSITY_STEP: 0.05,
  DEFAULT_CHAR_DENSITY: 0.7,       // 更密 (原 0.6)
  GLOW_INTENSITY_MIN: 0.5,
  GLOW_INTENSITY_MAX: 2,
  GLOW_INTENSITY_STEP: 0.1,
  DEFAULT_GLOW_INTENSITY: 1.4,     // 更强 (原 1.2)
  TRAIL_LENGTH_MIN: 0.1,
  TRAIL_LENGTH_MAX: 1,
  TRAIL_LENGTH_STEP: 0.05,
  DEFAULT_TRAIL_LENGTH: 0.6,       // 更长 (原 0.5)
  CHAR_SIZE_MIN: 4,
  CHAR_SIZE_MAX: 16,
  CHAR_SIZE_STEP: 1,
  DEFAULT_CHAR_SIZE: 10,           // 更大 (原 8)
  SHOW_ORIGINAL_MIN: 0,
  SHOW_ORIGINAL_MAX: 1,
  SHOW_ORIGINAL_STEP: 0.05,
  DEFAULT_SHOW_ORIGINAL: 0.4,      // 更清晰 (原 0.3)
} as const;

export const RETRO_PIXEL = {
  PIXEL_SIZE_MIN: 1,              // 更小的最小值
  PIXEL_SIZE_MAX: 16,
  PIXEL_SIZE_STEP: 1,
  DEFAULT_PIXEL_SIZE: 3,           // 更小更精细 (原 4)
  PALETTE_MODE_MIN: 0,
  PALETTE_MODE_MAX: 3,
  PALETTE_MODE_STEP: 1,
  DEFAULT_PALETTE_MODE: 1,         // SNES (原 0 NES)
  DITHER_STRENGTH_MIN: 0,
  DITHER_STRENGTH_MAX: 1,
  DITHER_STRENGTH_STEP: 0.05,
  DEFAULT_DITHER_STRENGTH: 0.45,   // 略轻 (原 0.5)
  CRT_EFFECT_MIN: 0,
  CRT_EFFECT_MAX: 1,
  CRT_EFFECT_STEP: 0.05,
  DEFAULT_CRT_EFFECT: 0.25,        // 更轻 (原 0.3)
  COLOR_DEPTH_MIN: 4,
  COLOR_DEPTH_MAX: 64,
  COLOR_DEPTH_STEP: 4,
  DEFAULT_COLOR_DEPTH: 24,         // 更多颜色 (原 16)
  SCANLINE_BRIGHTNESS_MIN: 0.5,
  SCANLINE_BRIGHTNESS_MAX: 1,
  SCANLINE_BRIGHTNESS_STEP: 0.05,
  DEFAULT_SCANLINE_BRIGHTNESS: 0.9, // 更亮 (原 0.85)
} as const;

export const PALETTE_MODES = [
  { mode: 0, label: 'NES' },
  { mode: 1, label: 'SNES' },
  { mode: 2, label: 'GB' },
  { mode: 3, label: '自定义' },
] as const;
